### ISSUE TITLE
我也在做类似的东西，请教

### ISSUE THREAD

**Issue by 11tools** [teenagerold/FPGA_SDR-mars-board#1]
1.我用的是xlinx ise ，里面没有nco，用dds可否代替
2.AD9203 硬件上前端可以加LNA吗，我看俄文是没有的加的，加了的话，对程序有没有影响
3.看他系统时钟好像才50M，怎么保障NCO产生的频率的精度的

**Comment by teenagerold** [comment]
1.可以，选择sin,cos双路输出就行。
2.可以加，就注意一下ADC如果是单端输入，需要在代码里减去直流偏置。
3.NCO输出频率精度？指的是频率分辨率还是频率稳定度？频率分辨率是参考时钟除以2^M，M是相位累加器字长，系统时钟50Mhz，M=32，频率分辨率等于0.01164Hz，足够了。频率稳定度和使用的晶振有关。

**Comment by 11tools** [comment]
谢谢了，解答了我长期的疑惑
